### ISSUE TITLE
Bozuk

### ISSUE THREAD

**Issue by dhDeneme** [burakcan/Kangaroo#1]
Calismiyor

**Comment by dhDeneme** [comment]
Calisti

**Comment by dhDeneme** [comment]
dfsgsdfgsdfg

**Comment by venkirocking2** [comment]
C:\Users\VE325836\Desktop\cd>npm start
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\VE325836\Desktop\cd\npm-debug.log




Here start script is missing and server file too may can any body help me please
