### ISSUE TITLE
Setup guide request

### ISSUE THREAD

**Issue by yarnball** [burakcan/Kangaroo#3]
Hi,

This looks like a very nice project. Could you please give setup instructions? I've run npm install , then npm run- but no success.

Thanks

**Comment by burakcan** [comment]
Hi, 
Since this is an old project (my first react project, three years ago), there was no webpack back then :) Also npm scripts was not popular.
You need to use grunt-cli to build the project. You can install it by :

```
npm install grunt-cli -g
```

and then build by `grunt`

**Comment by yarnball** [comment]
Thanks! Do you have any similar project I can test out? Wanting a simple react CRUD
